Automatic transcoding feature, RecordID, and $enter without args.
chebro/discord-voice-recorder pull request #16
Opened 2021-04-22 14:17 UTC by capthndsme

Implemented the following features:
Automatic transcoding feature
- Runs merge.js on record stop.
- Merge.js runs ffmpeg to transcode.
- This requires a record id feature to be implemented.

You can now enter without args. This will join the user's current voice channel.

Added JSON metadata.
- This contains who started the recording, and timestamps of voice start/end.

2021-04-23 15:52 UTC, chebro commented
@capthndsme hey there, thanks for contributing!

I'm a little busy with school atm, the changes look good on first glance (thanks to the detailed info), I'll go through it in detail sometime soon, hopefully before this month :)

2021-04-28 12:07 UTC, chebro requested changes
This is a good enhancement! I really like the guild lock thingy 😄  

There are just a few issues with the PR and I'm a bit iffy about the necessity of including metadata but overall, great work!

Also, the code formatting is a mess (including mine :P), I should probably add a pre commit hook to fix that.

2022-12-07 09:20 UTC, gamer50082 commented
Can you update this to fit with the new updated command.js as this contains the cannot find channel bug

2026-08-03 20:23 UTC, mdafreensh5afreen-lab commented
![Uploading Screenshot_2026-07-03-23-58-39-222_com.facebook.orca.jpg…]()

2026-08-03 20:26 UTC, mdafreensh5afreen-lab commented
> Can you update this to fit with the new updated command.js as this contains the cannot find channel bug

https://github.com/chebro/discord-voice-recorder/pull/16#issuecomment-1340636304

2026-08-10 23:23 UTC, capthndsme commented
Wow that weird bot bump made me remind of this merge request that I forgot. Anyway, I ran the source code through cursor and tested it manually, now it runs on typescript, discord.js 14, and modern nodejs (node 22). 
#28

2026-08-10 23:23 UTC, closed without merging